# Generated by Django 5.0.7 on 2024-07-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('automodel', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('number', models.IntegerField(default=0)),
                ('doors', models.IntegerField(default=0)),
                ('wheels', models.IntegerField(default=0)),
                ('tank_volume', models.IntegerField(default=0)),
            ],
        ),
    ]
