# Generated by Django 5.0.7 on 2024-07-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='doors',
            new_name='fuel_capacity',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='tank_volume',
            new_name='seats',
        ),
        migrations.AlterField(
            model_name='car',
            name='number',
            field=models.CharField(max_length=50),
        ),
    ]
