# Generated by Django 5.0.7 on 2024-07-29 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0004_deal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='user',
        ),
    ]
