# Generated by Django 5.0.7 on 2024-07-31 17:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0005_remove_car_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='date_rent_beg',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
